name: Rust

on: [push]

jobs:
  check:
    name: Rust project
    strategy:
      matrix:
        include:
          - toolchain: stable
          - toolchain: nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install relevant toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            override: true
      - run: rustc --version
      - run: cargo build --verbose
      - run: cargo test --verbose
